# Generated by Django 4.0.8 on 2026-04-24 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ipam.fields
import netbox_cmdb.fields


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('netbox_cmdb', '0001_initial'),
        ('netbox_cmdb', '0002_circuit'),
        ('netbox_cmdb', '0003_add_bgp_session'),
        ('netbox_cmdb', '0004_rework_bgp_model'),
        ('netbox_cmdb', '0005_alter_ordering_and_related_names'),
        ('netbox_cmdb', '0006_remove_nullable_charfield'),
        ('netbox_cmdb', '0007_routepolicyterm_description'),
        ('netbox_cmdb', '0008_prefixlist_ip_version'),
        ('netbox_cmdb', '0009_rework_route_pol_and_add_afisafi'),
        ('netbox_cmdb', '0010_add_new_route_policy_field'),
        ('netbox_cmdb', '0011_migrate_route_policies_to_route_policy'),
        ('netbox_cmdb', '0012_remove_old_route_policies_field'),
        ('netbox_cmdb', '0013_alter_routepolicyterm_set_next_hop'),
        ('netbox_cmdb', '0014_alter_afisafi_content_type_alter_afisafi_created_and_more'),
        ('netbox_cmdb', '0015_rename_local_asn_and_add_remote_asn'),
        ('netbox_cmdb', '0016_bgpsession_tenant'),
        ('netbox_cmdb', '0017_remove_bgppeergroup_maximum_prefixes'),
        ('netbox_cmdb', '0018_alter_bgppeergroup_remote_asn'),
        ('netbox_cmdb', '0019_afisafi_device_bgp_session'),
        ('netbox_cmdb', '0020_alter_afisafi_unique_together_and_more'),
        ('netbox_cmdb', '0021_alter_afisafi_device_bgp_session'),
        ('netbox_cmdb', '0022_bgpglobal'),
        ('netbox_cmdb', '0023_alter_bgpglobal_ecmp_and_more'),
        ('netbox_cmdb', '0024_alter_bgpglobal_ecmp_maximum_paths'),
        ('netbox_cmdb', '0025_alter_bgpcommunitylist_device_and_more'),
        ('netbox_cmdb', '0026_alter_devicebgpsession_local_address'),
        ('netbox_cmdb', '0027_remove_bgpcommunitylistterm_decision'),
        ('netbox_cmdb', '0028_remove_prefixlistterm_decision'),
        ('netbox_cmdb', '0029_vrf'),
        ('netbox_cmdb', '0030_alter_routepolicyterm_set_as_path_prepend'),
        ('netbox_cmdb', '0031_remove_bgpsession_status_bgpsession_state_and_more'),
        ('netbox_cmdb', '0032_bgpsession_monitoring_state'),
        ('netbox_cmdb', '0033_delete_vrf'),
        ('netbox_cmdb', '0034_vrf'),
        ('netbox_cmdb', '0035_vlan'),
        ('netbox_cmdb', '0036_deviceinterface'),
        ('netbox_cmdb', '0037_alter_vlan_unique_together_remove_vlan_device'),
        ('netbox_cmdb', '0038_alter_vrf_unique_together_remove_vrf_device'),
        ('netbox_cmdb', '0039_logicalinterface'),
        ('netbox_cmdb', '0040_snmpcommunity_snmp'),
        ('netbox_cmdb', '0041_portlayout'),
        ('netbox_cmdb', '0042_link'),
        ('netbox_cmdb', '0043_devicebgpsession_delay_open_timer'),
        ('netbox_cmdb', '0044_globalafisafi_redistributednetwork_aggregate'),
        ('netbox_cmdb', '0045_syslogserver_syslog'),
    ]

    dependencies = [
        ('dcim', '0160_squashed_0166'),
        ('tenancy', '0001_squashed_0012'),
        ('ipam', '0054_squashed_0067'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('organization_name', models.CharField(max_length=100, unique=True)),
                ('number', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967294)])),
            ],
            options={
                'verbose_name_plural': 'AS Numbers',
            },
        ),
        migrations.CreateModel(
            name='BGPCommunityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
            ],
            options={
                'verbose_name_plural': 'BGP community lists',
                'unique_together': {('name', 'device')},
            },
        ),
        migrations.CreateModel(
            name='BGPGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('router_id', models.CharField(blank=True, default='', max_length=100)),
                ('ebgp_administrative_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('ibgp_administrative_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('graceful_restart', models.BooleanField()),
                ('graceful_restart_time', models.PositiveIntegerField(blank=True, null=True)),
                ('ecmp', models.BooleanField(default=True)),
                ('ecmp_maximum_paths', models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(1)])),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
                ('local_asn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn')),
            ],
            options={
                'verbose_name': 'BGP global configuration',
            },
        ),
        migrations.CreateModel(
            name='BGPPeerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('enforce_first_as', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
                ('local_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn')),
                ('remote_asn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)sremote_asn', to='netbox_cmdb.asn')),
            ],
            options={
                'verbose_name_plural': 'BGP Peer Groups',
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('state', models.CharField(default='staging', max_length=50)),
                ('monitoring_state', models.CharField(default='disabled', max_length=50)),
                ('autonegotiation', models.BooleanField(default=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
                ('fec', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GlobalAfiSafi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('afi_safi_name', models.CharField(max_length=50)),
                ('bgp_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afi_safis', to='netbox_cmdb.bgpglobal')),
            ],
            options={
                'unique_together': {('bgp_global', 'afi_safi_name')},
            },
        ),
        migrations.CreateModel(
            name='PrefixList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_version', models.CharField(default='ipv4', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
            ],
            options={
                'unique_together': {('name', 'device')},
            },
        ),
        migrations.CreateModel(
            name='RoutePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
            ],
            options={
                'verbose_name_plural': 'Route Policies',
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SNMPCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('community', models.CharField(max_length=31)),
                ('type', models.CharField(default='readonly', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'SNMP Communities',
            },
        ),
        migrations.CreateModel(
            name='SyslogServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('server_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name_plural': 'Syslog Servers',
            },
        ),
        migrations.CreateModel(
            name='VRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)stenant', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'VRF',
                'verbose_name_plural': 'VRFs',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('vid', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)stenant', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'ordering': ['vid'],
                'unique_together': {('vid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Syslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
                ('server_list', models.ManyToManyField(blank=True, default=None, related_name='%(class)s_syslog_server', to='netbox_cmdb.syslogserver')),
            ],
            options={
                'verbose_name_plural': 'Syslog',
            },
        ),
        migrations.CreateModel(
            name='SNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.CharField(max_length=31)),
                ('contact', models.CharField(max_length=31)),
                ('community_list', models.ManyToManyField(blank=True, default=None, related_name='%(class)s_community', to='netbox_cmdb.snmpcommunity')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
            ],
            options={
                'verbose_name_plural': 'SNMP',
            },
        ),
        migrations.CreateModel(
            name='PortLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('label_name', models.CharField(max_length=64)),
                ('logical_name', models.CharField(max_length=64)),
                ('vendor_name', models.CharField(max_length=64)),
                ('vendor_short_name', models.CharField(max_length=64)),
                ('vendor_long_name', models.CharField(max_length=64)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_device_type', to='dcim.devicetype')),
                ('network_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_network_role', to='dcim.devicerole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(default='staging', max_length=50)),
                ('monitoring_state', models.CharField(default='disabled', max_length=50)),
                ('interface_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_interface_a', to='netbox_cmdb.deviceinterface')),
                ('interface_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_interface_b', to='netbox_cmdb.deviceinterface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceBGPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('enforce_first_as', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('delay_open_timer', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)])),
                ('maximum_prefixes', models.PositiveIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
                ('local_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_address', to='ipam.ipaddress')),
                ('local_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn')),
                ('peer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.bgppeergroup')),
                ('route_policy_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_in', to='netbox_cmdb.routepolicy')),
                ('route_policy_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_out', to='netbox_cmdb.routepolicy')),
            ],
            options={
                'verbose_name_plural': 'Device BGP Sessions',
            },
        ),
        migrations.CreateModel(
            name='BGPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(default='staging', max_length=50)),
                ('monitoring_state', models.CharField(default='disabled', max_length=50)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netbox_cmdb.circuit')),
                ('peer_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_a', to='netbox_cmdb.devicebgpsession')),
                ('peer_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_b', to='netbox_cmdb.devicebgpsession')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'BGP Sessions',
            },
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='route_policy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_in', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='route_policy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_out', to='netbox_cmdb.routepolicy'),
        ),
        migrations.CreateModel(
            name='RoutePolicyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('decision', models.CharField(default='permit', max_length=10)),
                ('from_bgp_community', models.CharField(blank=True, max_length=100)),
                ('from_source_protocol', models.CharField(blank=True, max_length=32)),
                ('from_route_type', models.CharField(blank=True, max_length=32)),
                ('from_local_pref', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_local_pref', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_community', models.CharField(blank=True, max_length=100)),
                ('set_origin', models.CharField(blank=True, max_length=32)),
                ('set_metric', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_large_community', models.CharField(blank=True, max_length=100)),
                ('set_as_path_prepend_repeat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set_next_hop', netbox_cmdb.fields.CustomIPAddressField(blank=True, null=True)),
                ('from_bgp_community_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.bgpcommunitylist')),
                ('from_prefix_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.prefixlist')),
                ('route_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_policy_term', to='netbox_cmdb.routepolicy')),
                ('set_as_path_prepend_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn')),
            ],
            options={
                'verbose_name_plural': 'Route Policy terms',
                'ordering': ['sequence'],
                'unique_together': {('route_policy', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='RedistributedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('prefix', ipam.fields.IPNetworkField()),
                ('global_afi_safi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributed_networks', to='netbox_cmdb.globalafisafi')),
            ],
            options={
                'unique_together': {('global_afi_safi', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='PrefixListTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('prefix', ipam.fields.IPNetworkField()),
                ('le', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prefix_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_list_term', to='netbox_cmdb.prefixlist')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('prefix_list', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='LogicalInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('state', models.CharField(default='staging', max_length=50)),
                ('monitoring_state', models.CharField(default='disabled', max_length=50)),
                ('mtu', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(default=None, max_length=2)),
                ('mode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('ipv4_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ipv4_address', to='ipam.ipaddress')),
                ('ipv6_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ipv6_address', to='ipam.ipaddress')),
                ('native_vlan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_native_vlan', to='netbox_cmdb.vlan')),
                ('parent_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='netbox_cmdb.deviceinterface')),
                ('tagged_vlans', models.ManyToManyField(blank=True, default=None, related_name='%(class)s_tagged_vlans', to='netbox_cmdb.vlan')),
                ('untagged_vlan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_untagged_vlan', to='netbox_cmdb.vlan')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_vrf', to='netbox_cmdb.vrf')),
            ],
            options={
                'unique_together': {('index', 'parent_interface')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bgppeergroup',
            unique_together={('device', 'name')},
        ),
        migrations.CreateModel(
            name='BGPCommunityListTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('community', models.CharField(max_length=100)),
                ('bgp_community_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_community_list_term', to='netbox_cmdb.bgpcommunitylist')),
            ],
            options={
                'verbose_name_plural': 'BGP community list terms',
                'ordering': ['sequence'],
                'unique_together': {('bgp_community_list', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('prefix', ipam.fields.IPNetworkField()),
                ('global_afi_safi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='netbox_cmdb.globalafisafi')),
            ],
            options={
                'unique_together': {('global_afi_safi', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='AfiSafi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('afi_safi_name', models.CharField(max_length=50)),
                ('device_bgp_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afi_safis', to='netbox_cmdb.devicebgpsession')),
                ('route_policy_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_in', to='netbox_cmdb.routepolicy')),
                ('route_policy_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_out', to='netbox_cmdb.routepolicy')),
            ],
            options={
                'unique_together': {('device_bgp_session', 'afi_safi_name')},
            },
        ),
    ]
